/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestDemo: typeof import('./src/components/TestDemo.vue')['default']
    VideoContainer: typeof import('./src/components/VideoContainer.vue')['default']
    VideoFramesViewer: typeof import('./src/components/VideoFramesViewer.vue')['default']
  }
}

// For TSX support
declare global {
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TestDemo: typeof import('./src/components/TestDemo.vue')['default']
  const VideoContainer: typeof import('./src/components/VideoContainer.vue')['default']
  const VideoFramesViewer: typeof import('./src/components/VideoFramesViewer.vue')['default']
}